#!/usr/bin/env node
'use strict';
var argv = require('minimist')(process.argv.slice(2));
let fname=argv._[0]
const fs = require('fs');
let rawdata = fs.readFileSync(fname);
var pp=require("json-stringify-pretty-compact");
let j=JSON.parse(rawdata);
console.log(pp(j));;
